"""add_unique_profile_user_id

Revision ID: 56a52e815b45
Revises: f5e66a1b39b8
Create Date: 2026-02-08 16:03:12.421862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56a52e815b45'
down_revision: Union[str, Sequence[str], None] = 'f5e66a1b39b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_profile_user_id', 'profile', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_profile_user_id', 'profile', type_='unique')
    # ### end Alembic commands ###
