"""add_refresh_token_version_and_expand_totp_secret

Revision ID: c7cef34a534d
Revises: 56a52e815b45
Create Date: 2026-02-08 16:18:12.397601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7cef34a534d'
down_revision: Union[str, Sequence[str], None] = '56a52e815b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'refresh_token_version',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
    )
    op.alter_column('user', 'refresh_token_version', server_default=None)
    op.alter_column('user', 'totp_secret',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'totp_secret',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('user', 'refresh_token_version')
    # ### end Alembic commands ###
