"""Added is_2fa_enabled and totp_secret to user table

Revision ID: f5e66a1b39b8
Revises: 3010c6b43067
Create Date: 2025-11-28 22:58:51.477922

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5e66a1b39b8"
down_revision: Union[str, Sequence[str], None] = "3010c6b43067"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_2fa_enabled", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("totp_secret", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "totp_secret")
    op.drop_column("user", "is_2fa_enabled")
    # ### end Alembic commands ###
